### PR TITLE
Replace chrono dependency with humantime

### PR DESCRIPTION
**Pull request by MomoLangenstein**
Avoids [RUSTSEC-2020-0071](https://rustsec.org/advisories/RUSTSEC-2020-0071) and [RUSTSEC-2020-0159](https://rustsec.org/advisories/RUSTSEC-2020-0159) vulnerabilities in crates using `tskit`

### CODE REVIEW

**Comment by molpopgen** [comment]
Does this give UTC with local offsets, or plain UTC?

**Comment by MomoLangenstein** [comment]
> Does this give UTC with local offsets, or plain UTC?

`std::time::SystemTime` gives just pure UTC. Since fixing [RUSTSEC-2020-0159](https://rustsec.org/advisories/RUSTSEC-2020-0159) seems to require reimplementing a libc function (to get the local time zone) in Rust, getting the local timestamp in a non-vulnerable way will likely take some time. Once it is fixed, you could then switch back if you wanted.

**Comment by molpopgen** [comment]
Sounds great.  I'll dig in more tomorrow.  I imagine I'll merge this and make a release after adding a security audit action.

**Comment by molpopgen** [comment]
I just pulled this and looked at the docs--are you happy with the doc examples still using chrono to decode the time values?

**Pull request merged**
